// packages/solid/src/routes/demos/column-filtering.tsx
import { type JSX, createMemo, createSignal, createEffect, untrack } from 'solid-js'
import debounce from 'lodash-es/debounce'
import {
  DerivedColumn,
  FilterFn,
  ItemId,
  darkTheme,
  lightTheme,
  GroupedColumns,
} from '@lightfin/datagrid'
import { DataGrid, type N } from '@lightfin/solid-datagrid'
import rangeSlider from 'range-slider-input'

import { Input } from 'src/components/Input'
import { Select } from 'src/components/Select'
import { OpenLinkIcon, SliderIcon } from 'src/components/Icons'
import { IconButton } from 'src/components/IconButton'
import ignData from 'src/demo-data/ign_data.json'
import { DemoProps } from './types'

import '@lightfin/datagrid/dist/styles.css'
import 'range-slider-input/dist/style.css'
import styles from './ColumnFiltering.module.css'

// Our IGN data stops in 2016 so lets pretend it's current
const ignNowDate = new Date()
ignNowDate.setFullYear(2016)

const ignPlatforms = Array.from<string>(
  (ignData as any[]).reduce((set, item) => {
    set.add(item.platform)
    return set
  }, new Set())
).sort()

const ignScorePhrases = Array.from<string>(
  (ignData as any[]).reduce((set, item) => {
    set.add(item.scorePhrase)
    return set
  }, new Set())
).sort()

const ignGenres = Array.from<string>(
  (ignData as any[]).reduce((set, item) => {
    if (item.genre) {
      set.add(item.genre)
    }
    return set
  }, new Set())
).sort()

const editorsChoices = Array.from<string>(
  (ignData as any[]).reduce((set, item) => {
    set.add(item.editorsChoice)
    return set
  }, new Set())
).sort()

export function TextFilter({
  type,
  onChange,
}: {
  type?: JSX.InputHTMLAttributes<HTMLInputElement>['type']
  onChange: (value: string) => void
}) {
  const [value, setValue] = createSignal('')
  return (
    <Input
      type={type}
      value={value()}
      style={{ padding: '0.25em' }}
      onChange={e => {
        setValue(e.currentTarget.value)
        onChange(e.currentTarget.value)
      }}
    />
  )
}

export function SelectFilter({
  options,
  onChange,
}: {
  options: string[]
  onChange: (value: string) => void
}) {
  const [value, setValue] = createSignal('')
  return (
    <Select
      value={value()}
      style={{ padding: '0.25em' }}
      onChange={e => {
        setValue(e.currentTarget.value)
        onChange(e.currentTarget.value)
      }}
      options={[
        {
          value: '',
          label: 'Choose',
        },
      ].concat(
        options.map(v => ({
          value: v,
          label: v,
        }))
      )}
    />
  )
}

export function RangeFilter({
  min,
  max,
  onChange,
}: {
  min: number
  max: number
  onChange: (value: [min: number, max: number]) => void
}) {
  let rangeSliderRef: HTMLDivElement | undefined
  const [value, setValue] = createSignal<[min: number, max: number]>([min, max])

  createEffect(() => {
    if (rangeSliderRef) {
      const rangeSliderElement = rangeSlider(rangeSliderRef, {
        min,
        max,
        value: untrack(value),
        onInput: (values: [min: number, max: number]) => {
          setValue(values)
          onChange(values)
        },
      })
    }
  })

  return (
    <IconButton class={styles.popoverBtn} aria-labelledby="range filter popup">
      <SliderIcon style={{ height: '10px' }} />
      <div class={styles.popover}>
        <div
          ref={rangeSliderRef}
          // min={min}
          // max={max}
          // value={value}
          // onInput={(values: [min: number, max: number]) => {
          //   setValue(values)
          //   onChange(values)
          // }}
        />
      </div>
    </IconButton>
  )
}

export interface Game {
  id: number
  scorePhrase: string
  title: string
  url: string
  platform: string
  score: number
  genre: string
  editorsChoice: 'Y' | 'N'
  releaseYear: number
  releaseMonth: number
  releaseDay: number
}

const gameData = ignData as Game[]

const gameColumns: GroupedColumns<Game, JSX.Element> = [
  {
    key: 'url',
    header: null,
    getValue: d => (
      <a
        href={`https://ign.com${d.url}`}
        target="blank"
        title="Open game in new tab"
        style={{ color: 'var(--linkColor)' }}
      >
        <OpenLinkIcon style={{ height: '16px' }} />
      </a>
    ),
    width: 50,
    pin: 'start',
  },
  {
    key: 'id',
    header: 'ID',
    getValue: d => d.id,
    width: 80,
    filterComponent: onChange => <TextFilter type="number" onChange={onChange} />,
    filterFn: (item, filterValue) =>
      filterValue ? item.id === Number(filterValue) : true,
  },
  {
    key: 'title',
    header: 'Title',
    getValue: d => d.title,
    width: 200,
    filterComponent: onChange => <TextFilter type="search" onChange={onChange} />,
    filterFn: (item, value) => item.title.toLowerCase().includes(value.toLowerCase()),
  },
  {
    key: 'platform',
    header: 'Platform',
    getValue: d => d.platform,
    width: 160,
    filterComponent: onChange => (
      <SelectFilter options={ignPlatforms} onChange={onChange} />
    ),
    filterFn: (item, filterValue) => (filterValue ? item.platform === filterValue : true),
  },
  {
    key: 'score',
    header: 'Score',
    getValue: d => d.score,
    width: 80,
    filterComponent: onChange => <RangeFilter min={0} max={10} onChange={onChange} />,
    filterFn: (item, filterValues) =>
      filterValues?.length
        ? item.score >= filterValues[0] && item.score <= filterValues[1]
        : true,
  },
  {
    key: 'scorePhrase',
    header: 'Score Phrase',
    getValue: d => d.scorePhrase,
    filterComponent: onChange => (
      <SelectFilter options={ignScorePhrases} onChange={onChange} />
    ),
    filterFn: (item, filterValue) =>
      filterValue ? item.scorePhrase === filterValue : true,
  },
  {
    key: 'genre',
    header: 'Genre',
    getValue: d => d.genre,
    width: 120,
    filterComponent: onChange => <SelectFilter options={ignGenres} onChange={onChange} />,
    filterFn: (item, filterValue) => (filterValue ? item.genre === filterValue : true),
  },
  {
    key: 'editorsChoice',
    header: 'Pass',
    getValue: d => d.editorsChoice,
    width: 70,
    filterComponent: onChange => (
      <SelectFilter options={editorsChoices} onChange={onChange} />
    ),
    filterFn: (item, filterValue) =>
      filterValue ? item.editorsChoice === filterValue : true,
  },
  {
    key: 'release',
    header: 'Release',
    getValue: d =>
      new Date(`${d.releaseYear}-${d.releaseMonth}-${d.releaseDay}`).toLocaleDateString(),
    width: 120,
    filterComponent: onChange => (
      <SelectFilter
        options={['This year', 'Last year', 'This decade', 'All time']}
        onChange={onChange}
      />
    ),
    filterFn: (item, value: string) => {
      switch (value) {
        case 'This year':
          return item.releaseYear >= ignNowDate.getFullYear()
        case 'Last year':
          return item.releaseYear >= ignNowDate.getFullYear() - 1
        case 'This decade':
          return item.releaseYear >= ignNowDate.getFullYear() - 10
        default:
          return true
      }
    },
  },
]

export default function Demo({ theme }: DemoProps) {
  const [data, setData] = createSignal(gameData)

  // We save the value and the column.filterFn so that whenever a filter
  // changes we can apply all the filter functions to each row/item.
  const filterState: Record<ItemId, { filterValue: any; filterFn: FilterFn<Game> }> = {}

  // Filter the data after a delay when a filter changes
  const filterData = createMemo(() =>
    debounce((column: DerivedColumn<Game, N>, filterValue: string) => {
      const state = Object.assign(filterState.current, {
        [column.key]: {
          filterValue,
          filterFn: column.filterFn,
        },
      })

      setData(
        gameData.filter(item =>
          Object.values(state).every(
            ({ filterValue, filterFn }) => filterFn?.(item, filterValue) ?? true
          )
        )
      )
    }, 100)
  )

  return (
    <DataGrid<Game>
      columns={gameColumns}
      data={data()}
      getRowId={d => d.id}
      theme={theme === 'light' ? lightTheme : darkTheme}
      onFiltersChange={filterData}
    />
  )
}

// packages/docs/src/pages/docs/ColumnFiltering.tsx
import {
  Code,
  H1,
  P,
  PageButton,
  HGroup,
  Section,
  A,
  H3,
  H2,
  CodeBlock,
} from 'src/components/DocTypography'
import { useFrameworkTabs } from 'src/components/FrameworkTabContext'
import { Tabs } from 'src/components/Tabs'
import { Demo } from 'src/components/Demo'

export default function Doc() {
  const { state, changeTab } = useFrameworkTabs()

  return (
    <div>
      <H1>Column Filtering</H1>
      <Section>
        <P>
          If you want to search across all columns see{' '}
          <A href="/docs/guides/global-search">Global Search</A>
        </P>
        <H2>Column props</H2>
        <P>
          You can implement filtering by customizing the column header. There are two
          props which control filtering:
        </P>
        <H3>filterComponent</H3>
        <P>
          A callback which is passed an <Code>onChange</Code> handler and should return
          the column filtering component. The component should define the filter value
          locally (useState/setState) and also call <Code>onChange</Code> at the same time
          as updating local state.
        </P>
        <P>For example:</P>
        <Tabs activeTabId={state.activeTabId} onTabPress={changeTab}>
          {[
            {
              id: 'react',
              label: 'React',
              component: (
                <CodeBlock lang="typescript">{`
                // filterComponent: onChange => (
                //   <TextFilter onChange={onChange} />
                // ),
                function TextFilter({ onChange }: { onChange: (value: string) => void }) {
                  const [value, setValue] = useState('')
                  return (
                    <Input
                      type="search"
                      value={value}
                      onChange={e => {
                        setValue(e.currentTarget.value)
                        onChange(e.currentTarget.value)
                      }}
                    />
                  )
                }
              `}</CodeBlock>
              ),
            },
            {
              id: 'solid',
              label: 'Solid',
              component: (
                <CodeBlock lang="typescript">{`
                // filterComponent: onChange => (
                //   <TextFilter onChange={onChange} />
                // ),
                function TextFilter({ onChange }: { onChange: (value: string) => void }) {
                  const [value, setValue] = createSignal('')
                  return (
                    <Input
                      type="search"
                      value={value()}
                      onChange={e => {
                        setValue(e.currentTarget.value)
                        onChange(e.currentTarget.value)
                      }}
                    />
                  )
                }
              `}</CodeBlock>
              ),
            },
          ]}
        </Tabs>
        <H3>filterFn</H3>
        <P>
          A function used to filter data by this column's filter value. It's passed{' '}
          <Code>(item, filerValue)</Code>, where item is a row/item of data and value is
          the filter value for this column. Returning <Code>false</Code> means filter the
          item out of the datagrid.
        </P>
        <P>For example:</P>
        <CodeBlock lang="typescript">{`
          filterFn: (item, filterValue) =>
            item.title.toLowerCase().includes(filterValue.toLowerCase())
        `}</CodeBlock>
        <H2>DataGrid props</H2>
        <P>
          Finally, there are two props on the DataGrid, one which must be implemented.
        </P>
        <H3>onFilterChange (required for filtering)</H3>
        <P>
          Called each time a column filter calls <Code>onChange</Code>. This is the
          callback where you filter data.
        </P>
        <P>
          Typically you'll want to add a small debounce for that filters where the user
          types or adjusts a silder.
        </P>
        <Tabs activeTabId={state.activeTabId} onTabPress={changeTab}>
          {[
            {
              id: 'react',
              label: 'React',
              component: (
                <CodeBlock lang="typescript">{`
                // Save the filterValues and functions in an object
                const filterState = useRef<
                  Record<ItemId, { filterValue: any; filterFn: FilterFn<Game> }>
                >({})
                
                // Filter the data after a delay when a filter changes
                const filterData = useMemo(
                  () =>
                    debounce(
                      (column: DerivedColumn<Game, N>, filterValue: string) => {
                        const state = Object.assign(filterState.current, {
                          [column.key]: {
                            filterValue,
                            filterFn: column.filterFn,
                          },
                        })
                
                        setData(
                          gameData.filter(item =>
                            Object.values(state).every(
                              ({ filterValue, filterFn }) =>
                                filterFn?.(item, filterValue) ?? true
                            )
                          )
                        )
                      },
                      100
                    ),
                  []
                )

                return (
                  <DataGrid
                    // ...
                    onFiltersChange={filterData}
                  />
                )
              `}</CodeBlock>
              ),
            },
            {
              id: 'solid',
              label: 'Solid',
              component: (
                <CodeBlock lang="typescript">{`
                // Save the filterValues and functions in an object
                const filterState: Record<ItemId, { filterValue: any; filterFn: FilterFn<Game> }> = {}
                
                // Filter the data after a delay when a filter changes
                const filterData = createMemo(() =>
                  debounce(
                    (column: DerivedColumn<Game, N>, filterValue: string) => {
                      const state = Object.assign(filterState.current, {
                        [column.key]: {
                          filterValue,
                          filterFn: column.filterFn,
                        },
                      })
              
                      setData(
                        gameData.filter(item =>
                          Object.values(state).every(
                            ({ filterValue, filterFn }) =>
                              filterFn?.(item, filterValue) ?? true
                          )
                        )
                      )
                    },
                    100
                  )
                )

                return (
                  <DataGrid
                    // ...
                    onFiltersChange={filterData}
                  />
                )
              `}</CodeBlock>
              ),
            },
          ]}
        </Tabs>
        <H3>filterRowHeight</H3>
        <P>The height of the filter row. Defaults to 40px.</P>
      </Section>
      <Section>
        <Tabs activeTabId={state.activeTabId} onTabPress={changeTab}>
          {[
            {
              id: 'react',
              label: 'React',
              component: (
                <Demo
                  demoUrl={`${
                    import.meta.env.VITE_REACT_DEMO_BASE_URL
                  }/demos/column-filtering`}
                  demoSrc={import('/../react/src/demos/ColumnFiltering.tsx?raw')}
                  height={407}
                />
              ),
            },
            {
              id: 'solid',
              label: 'Solid',
              component: (
                <Demo
                  demoUrl={`${
                    import.meta.env.VITE_REACT_DEMO_BASE_URL
                  }/demos/column-filtering`}
                  demoSrc={import('/../react/src/demos/ColumnFiltering.tsx?raw')}
                  height={407}
                />
              ),
            },
          ]}
        </Tabs>
      </Section>
      <HGroup justifyEnd>
        <PageButton href="/docs/columns/grouping" secondaryLabel="Previous">
          Column Grouping
        </PageButton>
        <PageButton href="/docs/columns/pinning" secondaryLabel="Next">
          Column Pinning
        </PageButton>
      </HGroup>
    </div>
  )
}
