// packages/react/src/components/DemoContainer/DemoContainer.tsx
import styles from './DemoContainer.module.css'

interface DemoContainerProps {
  height: number
  children?: React.ReactNode
}

export function DemoContainer({ children, height }: DemoContainerProps) {
  return (
    <div className={styles.container} style={{ height: `${height}px` }}>
      {children}
    </div>
  )
}

// packages/solid/src/components/DemoContainer/DemoContainer.tsx
import { JSX } from 'solid-js'
import styles from './DemoContainer.module.css'

interface DemoContainerProps {
  height: string
  children?: JSX.Element
}

export function DemoContainer({ children, height }: DemoContainerProps) {
  return (
    <div class={styles.container} style={{ height }}>
      {children}
    </div>
  )
}
